const state={catalog:null,community:{projects:[],threads:[]}};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){const c=state.catalog||{};const mods=c.packages||[];document.querySelector('#stats').innerHTML=[[''+mods.length,'public packages'],[''+(c.research||[]).length,'research records'],[''+(c.knowledge||[]).length,'knowledge entries'],['v'+(c.schema_version||1),'catalog contract']].map(x=>`<div class="stat"><strong>${esc(x[0])}</strong><span>${esc(x[1])}</span></div>`).join('');
const query=(document.querySelector('#search').value||'').toLowerCase();document.querySelector('#mod-grid').innerHTML=mods.filter(m=>JSON.stringify(m).toLowerCase().includes(query)).map(m=>`<article class="card"><span class="badge">${esc(m.package_type||'mod')} · ${esc(m.version)}</span><h3>${esc(m.name)}</h3><p>${esc(m.description||'No public description yet.')}</p><small>${esc(m.author||'Unknown author')} · ${esc((m.required_builds||[]).join(', ')||'Build context pending')}</small><br><a class="detail-link" href="#mod/${encodeURIComponent(m.id)}">Open record →</a></article>`).join('')||'<p class="muted">No records match this search.</p>';
document.querySelector('#research-list').innerHTML=(c.research||[]).map(r=>`<article class="record"><small>${esc(r.game_build||'build pending')}</small><strong>${esc(r.title)}</strong><p>${esc(r.hypothesis)}</p><span class="badge">${esc(r.status)} · ${esc(r.evidence_count)} evidence · ${esc(r.reproduction_step_count||0)} reproduction steps</span></article>`).join('')||'<p class="muted">No public research records yet.</p>';
document.querySelector('#knowledge-grid').innerHTML=(c.knowledge||[]).map(k=>`<article class="knowledge"><span class="badge">${esc(k.category)} · v${esc(k.version||1)}</span><h3>${esc(k.title)}</h3><p>${esc(k.summary)}</p><small>${esc((k.tags||[]).join(' · '))}</small></article>`).join('')||'<p class="muted">No public knowledge entries yet.</p>';}
document.querySelector('#community-grid').innerHTML=[...(state.community.projects||[]).map(p=>`<article><span>PROJECT · ${esc(p.status)}</span><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p><a href="#community">${esc((p.linked_records||[]).length)} linked public records →</a></article>`),...(state.community.threads||[]).map(t=>`<article><span>DISCUSSION · ${esc(t.status)}</span><h3>${esc(t.title)}</h3><p>${esc(t.summary)}</p><a href="#community">${esc(t.post_count||0)} public post(s) →</a></article>`)].join('')||'<p class="muted">No public community records yet.</p>';}
function renderDetail(){const match=location.hash.match(/^#mod\/(.+)$/);const id=match&&decodeURIComponent(match[1]);const mod=(state.catalog?.packages||[]).find(item=>item.id===id);let panel=document.querySelector('#detail');if(!mod){if(panel)panel.remove();return}if(!panel){panel=document.createElement('section');panel.id='detail';panel.className='detail-panel section';document.querySelector('main').prepend(panel)}panel.innerHTML=`<p class="eyebrow">MOD DETAIL</p><h2>${esc(mod.name)}</h2><p class="muted">${esc(mod.description||'No public description yet.')}</p><div class="detail-meta"><span>Author · ${esc(mod.author||'Unknown')}</span><span>Version · ${esc(mod.version)}</span><span>Type · ${esc(mod.package_type||'mod')}</span><span>Builds · ${esc((mod.required_builds||[]).join(', ')||'Not specified')}</span></div><a class="button" href="#mods">← Back to catalog</a>`}
Promise.all([fetch('embervault-catalog.json').then(r=>r.json()),fetch('content/community.json').then(r=>r.json())]).then(([catalog,community])=>{state.catalog=catalog;state.community=community;render();renderDetail()}).catch(()=>{state.catalog={};render()});document.querySelector('#search').addEventListener('input',render);
window.addEventListener('hashchange',renderDetail);
